folio-org/mod-oai-pmh

Jenkinsfile
NEWS.md
docker/docker-entrypoint.sh
pom.xml
src/main/resources/log4j.properties

1. Adding docker-entrypoint, log4j, pom
2. Updating News (version changed to 1.0.0), Jenkinsfile (disabling all the actions by default which will be enabled later on)

Modoaipmh 43 add common files

---

NEWS.md
descriptors/DeploymentDescriptor-template.json
descriptors/ModuleDescriptor-template.json

1. Required interfaces are specified 
2. Module Permissions are defined
3. Permissions & Permission sets are defined and assigned to endponits

Modoaipmh 4 define module/deployment descriptors

---

NEWS.md
README.md
pom.xml
src/main/java/org/folio/oaipmh/ResponseHelper.java

MODOAIPMH-15 Implement verb "Identify" - Updating News and Readme

---

src/main/java/org/folio/oaipmh/Request.java
src/main/java/org/folio/oaipmh/helpers/AbstractHelper.java
src/main/java/org/folio/oaipmh/helpers/GetOaiRepositoryInfoHelper.java
src/main/java/org/folio/oaipmh/helpers/VerbHelper.java
src/main/java/org/folio/rest/impl/OaiPmhImpl.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java

The PR contains proposal for refactoring endpoint helpers structure, namely:
- introduce common interface for helpers
- OAI-PMH request arguments holder class
- statically initialize a map with Verb as a key and corresponding implementation a a value
- get appropriate helper instance from endpoint impl method

MODOAIPMH-14 OAI-PMH: Implement verb "ListSets"

---

pom.xml
src/main/java/org/folio/oaipmh/helpers/AbstractHelper.java
src/main/java/org/folio/oaipmh/helpers/GetOaiIdentifiersHelper.java
src/main/java/org/folio/oaipmh/helpers/GetOaiSetsHelper.java
src/main/java/org/folio/rest/impl/OaiPmhImpl.java
src/test/java/org/folio/oaipmh/MetadataPrefixTest.java
src/test/java/org/folio/oaipmh/mappers/MarcXmlMapperTest.java
src/test/java/org/folio/oaipmh/mappers/XSLTMapperTest.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java
src/test/java/org/folio/rest/impl/OkapiMockServer.java

- The main logic implementation
- Validation of the parameters (MODOAIPMH-37)
- Handle default set (MODOAIPMH-39)
- Migrating all unit tests to junit5 and removing junit4 dependency

MODOAIPMH-36 Implement verb "ListIdentifiers"

---

src/main/java/org/folio/oaipmh/helpers/CQLQueryBuilder.java
src/main/java/org/folio/oaipmh/helpers/GetOaiIdentifiersHelper.java
src/main/java/org/folio/oaipmh/helpers/InstancesStorageHelper.java
src/main/java/org/folio/oaipmh/helpers/InventoryStorageHelper.java
src/test/java/org/folio/oaipmh/helpers/InventoryStorageHelperTest.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java

add support for date range queries

MODOAIPMH-38 Date ranges

---

NEWS.md

MODOAIPMH-20 Implement verb "ListIdentifiers"

---

src/main/java/org/folio/oaipmh/Constants.java
src/main/java/org/folio/oaipmh/ResponseHelper.java
src/main/java/org/folio/oaipmh/helpers/AbstractHelper.java
src/main/java/org/folio/oaipmh/helpers/GetOaiMetadataFormatsHelper.java
src/main/java/org/folio/oaipmh/helpers/GetOaiRecordsHelper.java
src/main/java/org/folio/oaipmh/helpers/VerbHelper.java
src/main/java/org/folio/rest/impl/InitAPIs.java
src/main/java/org/folio/rest/impl/OaiPmhImpl.java
src/test/java/org/folio/oaipmh/ResponseHelperTest.java
src/test/java/org/folio/rest/impl/InitAPIsTest.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java
src/test/resources/config/config.properties

- Initial change to return Records
- Moving constants to separate class as suggested by sonar
- Refactor ResponseHelper#writeToString(...) method so it throws IllegalStateException if marshal operation cannot be done

MODOAIPMH-12 Implement verb "ListRecords"

---

src/main/java/org/folio/oaipmh/Constants.java
src/main/java/org/folio/oaipmh/helpers/GetOaiRepositoryInfoHelper.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java

MOD-OAI-PMH changes for including compression elements in the Identify response.

EDGOAIPMH-8 - OAI-PMH: Response compression

---

Jenkinsfile

Update CI config to publish module descriptor and Docker image.

---

pom.xml
src/main/java/org/folio/oaipmh/Constants.java
src/main/java/org/folio/rest/impl/OaiPmhImpl.java
src/test/java/org/folio/oaipmh/helpers/InventoryStorageHelperTest.java
src/test/java/org/folio/oaipmh/helpers/RepositoryConfigurationHelperTest.java

Fixed issue with "Bind Address already in use..." in unit tests

Modoaipmh 13 oai pmh backend configuration

---

src/main/java/org/folio/oaipmh/helpers/AbstractHelper.java
src/main/java/org/folio/oaipmh/helpers/GetOaiRepositoryInfoHelper.java
src/main/java/org/folio/oaipmh/helpers/InventoryStorageHelper.java
src/main/java/org/folio/oaipmh/helpers/RepositoryConfigurationHelper.java
src/main/java/org/folio/oaipmh/helpers/RepositoryConfigurationUtil.java
src/main/java/org/folio/rest/impl/OaiPmhImpl.java
src/test/java/org/folio/oaipmh/helpers/InventoryStorageHelperTest.java
src/test/java/org/folio/oaipmh/helpers/RepositoryConfigurationHelperTest.java
src/test/java/org/folio/oaipmh/helpers/RepositoryConfigurationUtilTest.java
src/test/java/org/folio/rest/impl/OkapiMockServer.java

- RepositoryConfigurationHelper for each tenant keeps its configuration in VertxContext

MODOAIPMH-62-OAI-PMH-Backend-Configuration-store-configs-per-tenant

---

descriptors/ModuleDescriptor-template.json
src/test/resources/instance-storage/instances/instances_10.json
src/test/resources/instance-storage/instances/instances_11_totalRecords_100.json
src/test/resources/instance-storage/instances/instances_2_lastWithStorageError500.json

Align `alternativeTitles` in test samples

Require `instance-storage` 6.0

---

descriptors/ModuleDescriptor-template.json

Updating SRS interface version to v2 and updating required permissions

MODOAIPMH-66 Upgrade to source-record-storage 2.0 interface

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

https://issues.folio.org/browse/MODOAIPMH-74 - 1.1.0 Release
The dependencies are already in required versions
Updating NEWS

MODOAIPMH-74 - Release 1.0.3

---

NEWS.md
pom.xml

**Purpose:**
https://issues.folio.org/browse/MODOAIPMH-79 - release 1.2.0
**Approach:**
Update NEWS.md

MODOAIPMH-76 Release 1.2.0

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

**Purpose:**
https://issues.folio.org/browse/MODOAIPMH-78 - release 1.2.1
**Approach:**
- Update NEWS.md
- Update interface dependencies

Release mod-oai-pmh 1.2.1

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
ramls/oai-pmh.raml

Release v2.0.0 for inclusion in Edelweiss (Q4/2019)
See [MODOAIPMH-87](https://issues.folio.org/browse/MODOAIPMH-87)
**NOTE**:  I have not yet run the mvn command to bump the versions and create the tag

Release 2.0.0

---

NEWS.md
pom.xml

https://issues.folio.org/browse/MODOAIPMH-91
Release 2.1.0
* Updated release notes

MODOAIPMH-91 release 2.1.0

---

src/main/java/org/folio/oaipmh/mappers/PropertyNameMapper.java
src/main/java/org/folio/rest/impl/ModTenantAPI.java

###PURPOSE
Fix issue with inconsistency of configuration names regarding frontend config names contract

Modoaipmh 100

---

src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java

Reverse "0" and "1" into 999 general info "suppress discovery" subfield.
Flase was 1, now is 0.
True was 0, now is 1.
Fix issue with oai_dc format.

Add the suppressDiscovery flag into OAI-PMH feed

---

src/main/java/org/folio/oaipmh/helpers/storage/AbstractStorageHelper.java
src/test/java/org/folio/oaipmh/helpers/StorageHelperTest.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java

Add to the request to source-record-storage which is created in mod-oai-pmh until parameter with the current date.
[https://issues.folio.org/browse/MODOAIPMH-112](url)

MODOAIPMH-112 Fix issue with the chain of records getting with resumptionToken

---

pom.xml

MODOAIPMH-137: Update to RMB v30

---

src/main/java/org/folio/oaipmh/helpers/streaming/BatchStreamWrapper.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java

Hotfixes for MODOAIPMH-117: Request holdings and items fields from inventory

[FIXES] Request holdings and items fields from inventory

---

pom.xml

Update SRS dependency to v4

---

pom.xml
src/main/java/org/folio/rest/impl/ModTenantAPI.java

Fix issue with posting configurations to mod-ocnfiguration while running TenantAPI & use ConfigurationCLient instead of HttpClientInterface

Modoaipmh 176

---

pom.xml
src/main/resources/log4j.properties
src/main/resources/log4j2.properties

Use log4j2.properties instead of log4j.properties

Use log4j2.properties

---

src/main/java/org/folio/oaipmh/Constants.java
src/main/java/org/folio/oaipmh/helpers/AbstractHelper.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/test/java/org/folio/rest/impl/OkapiMockServer.java

Implement support for date-only filtering in from and until request params.
1. /oai/records?verb=ListRecords&metadataPrefix=marc21_withholdings&until=2020-06-26 *NEW*
2. oai/records?verb=ListRecords&metadataPrefix=marc21_withholdings&until=2020-06-25T11:02:37Z *Was implemented earlier*

Implement date-only filtering for ListRecords and metadataprefix marc21_withholdings

---

README.md
pom.xml
src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java

- Add filtering in SRS client for GetRecord request
- Actualize readme
- Update SRS version

Fixes after updatig to SRSv4

---

NEWS.md
pom.xml

Temp release 3.0.4

---

pom.xml
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/oaipmh/helpers/configuration/ConfigurationHelper.java
src/main/java/org/folio/rest/impl/InitAPIs.java
src/main/java/org/folio/rest/impl/ModTenantAPI.java
src/main/java/org/folio/rest/impl/OaiPmhImpl.java
src/test/java/org/folio/rest/impl/InitAPIsTest.java
src/test/resources/config/test-config/test1.json
src/test/resources/config/test-config/test2.json

Enable Spring DI for mod-oai-pmh.
https://issues.folio.org/browse/MODOAIPMH-203

MODOAIPMH-203: Enable Spring DI for mod-oai-pmh

---

src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/main/resources/liquibase/tenant/changelog.xml
src/main/resources/liquibase/tenant/scripts/2020-07-27--19-17-fix_primary_key.xml

Hotfixes for oai-pmh
Jira: https://issues.folio.org/browse/MODOAIPMH-202

Fixes for oai pmh

---

pom.xml
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java

Fix maven build and resolve issue with unnecessary logging.
https://issues.folio.org/browse/MODOAIPMH-213

MODOAIPMH-213: Maven build test phase fails 

---

pom.xml

Increase the next development version after release

Update next development version

---

descriptors/ModuleDescriptor-template.json
ramls/oai-pmh-set.raml
src/main/java/org/folio/rest/impl/OaiPmhSetImpl.java
src/test/java/org/folio/rest/impl/OaiPmhSetImplTest.java

Renaming of set endpoints due to current inconsistencies with common approach for writing the raml files structure on project which is going to bring a problems in furthet CRUD API  implementation for "sets" and "filtering conditions".
https://issues.folio.org/browse/MODOAIPMH-218

MODOAIPMH-218: Rename sets endpoints 

---

src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java

##Purpose
Adding proper error handling when getting connection
jira: https://issues.folio.org/browse/EDGOAIPMH-51

EDGOAIPMH-51: Fail promise if get connection failed

---

src/main/java/org/folio/oaipmh/service/impl/SetServiceImpl.java

Fix problem with returning only 10 items of each filtering-condition type (locations, resource-types and etc.)
Jira: https://issues.folio.org/browse/MODOAIPMH-210

MODOAIPMH-210: Implement endpoint for getting values of all required filtering condition types.

---

ramls/schemas/dto/folioSetCollection.json
src/main/java/org/folio/oaipmh/dao/impl/SetDaoImpl.java
src/test/java/org/folio/oaipmh/service/impl/SetServiceImplTest.java
src/test/java/org/folio/rest/impl/OaiPmhSetImplTest.java

Add totalRecords to set list response.
https://issues.folio.org/browse/MODOAIPMH-223

MODOAIPMH-223: "totalRecords" isn't shown in response to GET /oai-pmh/sets request

---

src/main/java/org/folio/oaipmh/dao/impl/SetDaoImpl.java
src/main/resources/liquibase/tenant/changelog.xml
src/main/resources/liquibase/tenant/scripts/2020-08-20--12-00-enhance-set-table.xml
src/main/resources/liquibase/tenant/scripts/2020-08-28--11-00-add-unique-constraint-for-name-and-set_spec-columns.xml

Added forgotten file after merging a lot of PR's -> fix issues with database.
Jira: https://issues.folio.org/browse/MODOAIPMH-227

MODOAIPMH-227: Set table constraints don't work properly

---

descriptors/ModuleDescriptor-template.json

Need to increase database connection pool size and timeout value.
Jira: https://issues.folio.org/browse/MODOAIPMH-229
```
{
"name": "DB_QUERYTIMEOUT",
"value": "180000"
},
{
"name": "DB_MAXPOOLSIZE",
"value": "20"
}
```

MODOAIPMH-229: Increase postrgres pool connection size and timeout for module

---

descriptors/ModuleDescriptor-template.json

This will be done along with profiling of memory usage.

Change memory size

---

Dockerfile
Jenkinsfile
pom.xml

Upgrade to Open JDK 11
https://issues.folio.org/browse/MODOAIPMH-188

MODOAIPMH-188: POC: Update to java 11

---

pom.xml

Release mod-oai-pmh

---

src/main/java/org/folio/oaipmh/helpers/records/RecordMetadataManager.java
src/test/java/org/folio/oaipmh/helpers/records/RecordMetadataManagerTest.java
src/test/resources/metadata-manager/inventory_instance_whit_item_without_location.json
src/test/resources/metadata-manager/inventory_instance_with_item_without_call_number.json

Fix issues with NullPointerException when processing items with empty location or callNumber.
Jira: https://issues.folio.org/browse/MODOAIPMH-231

MODOAIPMH-231: NPE on ListRecords with metdataPrefix=marc21_withholdings

---

src/main/java/org/folio/oaipmh/helpers/records/RecordMetadataManager.java
src/main/java/org/folio/oaipmh/helpers/streaming/BatchStreamWrapper.java
src/test/java/org/folio/oaipmh/helpers/records/RecordMetadataManagerTest.java
src/test/resources/metadata-manager/inventory_instance_with_not_suppressed_from_discovery_item.json
src/test/resources/metadata-manager/inventory_instance_with_suppressed_from_discovery_item.json

Fix ussue with incorrect "suppress from discovert" value formatting.
Jira: https://issues.folio.org/browse/MODOAIPMH-219

MODOAIPMH-219: Item's suppress from discovery flag value isn't correct for "transfer" behavior

---

descriptors/DeploymentDescriptor-template.json
descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java
src/main/java/org/folio/oaipmh/helpers/AbstractHelper.java
src/main/java/org/folio/oaipmh/helpers/records/RecordMetadataManager.java
src/main/java/org/folio/oaipmh/helpers/streaming/BatchStreamWrapper.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/main/java/org/folio/oaipmh/validator/VerbValidator.java
src/test/java/org/folio/oaipmh/helpers/records/RecordMetadataManagerTest.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java
src/test/resources/metadata-manager/inventory_instance_whit_item_without_location.json
src/test/resources/metadata-manager/inventory_instance_with_item_without_call_number.json
src/test/resources/metadata-manager/inventory_instance_with_not_suppressed_from_discovery_item.json
src/test/resources/metadata-manager/inventory_instance_with_suppressed_from_discovery_item.json

Move hotfix commits from release branch to master.
Hotfixes include next tickets:
1. https://issues.folio.org/browse/EDGEOAIPMH-51
2. https://issues.folio.org/browse/MODOAIPMH-216
3. https://issues.folio.org/browse/MODOAIPMH-219
4. https://issues.folio.org/browse/MODOAIPMH-226
5. https://issues.folio.org/browse/MODOAIPMH-229
6. https://issues.folio.org/browse/MODOAIPMH-231
Jira: https://issues.folio.org/browse/MODOAIPMH-235

MODOAIPMH-235: Apply the release hotfixes to master

---

pom.xml

The change was requested by teammates.

Fixed issue with module logging, as requested by teammates

---

NEWS.md
pom.xml

MODOAIPMH (mod-oai-pmh) release

MODOAIPMH-238: MODOAIPMH (mod-oai-pmh) release 3.2.0

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

Release v3.2.1

---

pom.xml
src/test/java/org/folio/rest/impl/OaiPmhSetImplTest.java

Update RMB version up to 31.1.5 version which contains fixfing issues with database interaction.

MODOAIPMH-256: update rmb version up to 31.1.5

---

NEWS.md
pom.xml
src/test/java/org/folio/rest/impl/OaiPmhSetImplTest.java

Merge 3.2.3 release changes to master
Jira: https://issues.folio.org/browse/MODOAIPMH-257

MODOAIPMH-257: Release mod-oai-pmh v3.2.3

---

NEWS.md
pom.xml

Jira: https://issues.folio.org/browse/MODOAIPMH-277
Release mod-oai-pmh 3.2.6

MODOAIPMH-277: Release mod-oai-pmh 3.2.6

---

src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java

Jira: https://issues.folio.org/browse/MODOAIPMH-276
Pass onlyInstanceUpdateDate flag to inventory-hierarchy view when requesting instance ids in order to consider items and holdings dates as well. See more details in Jira-ticket comments.

MODOAIPMH-276: Changes to holdings or items are not triggering harvesting records with marc21_withholdings

---

NEWS.md
pom.xml

Jira: https://issues.folio.org/browse/MODOAIPMH-280
Release mod-oai-pmh 3.2.7

MODOAIPMH-280: Release mod-oai-pmh 3.2.7

---

src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java

An increasing number of attempts of selecting instances ids from the database.

FIx issue with requsting insatnce ids from databse

---

NEWS.md
pom.xml

Jira: https://issues.folio.org/browse/MODOAIPMH-281
Merge changes after maven release command.

MODOAIPMH-281: Release mod-oai-pmh 3.3.0

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

Jira: https://issues.folio.org/browse/MODOAIPMH-297
Release the 3.4.0 module.

MODOAIPMH-297: mod-oai-pmh-3.4.0 - Iris release

---

src/main/resources/liquibase/tenant/scripts/2020-07-16--10-00-create-instnace-ids-table.xml
src/main/resources/liquibase/tenant/scripts/2020-11-19--18-00-create-request-metadata-table.xml

Jira: https://issues.folio.org/browse/MODOAIPMH-303
Add index on id column which increases querying performance. 
As well in this PR I moved the scripts related to the instances table to the "create-instance-ids-table.xml" to keep all related changes in one file.

MODOAIPMH-303: Add index to mod-oai-pmh.instances table

---

NEWS.md
pom.xml

Jira: https://issues.folio.org/browse/MODOAIPMH-308
Merge release branch to master.

MODOAIPMH-308: Release mod-oai-pmh v3.4.1

---

src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java
src/main/java/org/folio/oaipmh/helpers/AbstractHelper.java
src/main/java/org/folio/oaipmh/helpers/GetOaiMetadataFormatsHelper.java
src/main/java/org/folio/oaipmh/helpers/response/ResponseHelper.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java

Jira: https://issues.folio.org/browse/MODOAIPMH-312
Fix issues with an increasing number of attempts to re-request srs in two times after each exception handler.

MODOAIPMH-312: Rerequesting of SRS doesn't work properly

---

NEWS.md
pom.xml

Jira: https://issues.folio.org/browse/MODOAIPMH-313
Merge release branch to master

MODOAIPMH-313: Release mod-oai-pmh v3.4.2

---

pom.xml

Jira: https://issues.folio.org/browse/MODOAIPMH-320
Fix issue with displaying 0% coverage by sonar cloud.
See comments at https://issues.folio.org/browse/FOLIO-3101

MODOAIPMH-320: 0% coverage reported by Sonarcloud for mod-oai-pmh

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java
src/main/java/org/folio/oaipmh/helpers/GetOaiMetadataFormatsHelper.java

Jira: https://issues.folio.org/browse/MODOAIPMH-331
Update srs interface version

MODOAIPMH-331: Update srs interface version up to 3.0

---

descriptors/ModuleDescriptor-template.json

MODOAIPMH-328 align dependency versions affected by Inventory's Optimistic lock

MODOAIPMH-328 align dependency versions affected by Inventory's Optimistic lock

---

src/main/java/org/folio/oaipmh/helpers/records/RecordMetadataManager.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java
src/test/java/org/folio/rest/impl/OkapiMockServer.java
src/test/resources/inventory_view/enriched_instance_no_items.json
src/test/resources/inventory_view/template/enriched_instance-template.json
src/test/resources/metadata-manager/electronic_access-empty.json
src/test/resources/metadata-manager/electronic_access-no_display_constant_generated.json
src/test/resources/metadata-manager/electronic_access-related_resource.json
src/test/resources/metadata-manager/electronic_access-resource.json
src/test/resources/metadata-manager/electronic_access-version_of_resource.json
src/test/resources/metadata-manager/inventory_instance_2_electronic_accesses.json
src/test/resources/metadata-manager/inventory_instance_whit_item_without_location.json
src/test/resources/metadata-manager/inventory_instance_with_1_item.json
src/test/resources/metadata-manager/inventory_instance_with_2_items.json
src/test/resources/metadata-manager/inventory_instance_with_item_without_call_number.json
src/test/resources/metadata-manager/inventory_instance_with_not_suppressed_from_discovery_item.json
src/test/resources/metadata-manager/inventory_instance_with_suppressed_from_discovery_item.json

Jira: https://issues.folio.org/browse/MODOAIPMH-283
The existing FOLIO implementation of the derived fields (effective location and effective call number) requires item records. The purpose of this story is to populate location and holdings information, following the logic of effective location/call number when the item data is not present.

MODOAIPMH-283 provide effective location and effective call number data when item record is not present

---

pom.xml
src/main/java/org/folio/oaipmh/WebClientProvider.java
src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java
src/main/java/org/folio/oaipmh/helpers/RepositoryConfigurationUtil.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/main/java/org/folio/oaipmh/service/impl/SetServiceImpl.java
src/main/java/org/folio/rest/impl/InitAPIs.java
src/main/java/org/folio/rest/impl/ModTenantAPI.java
src/main/java/org/folio/rest/impl/OaiPmhImpl.java
src/test/java/org/folio/oaipmh/helpers/RepositoryConfigurationUtilTest.java
src/test/java/org/folio/oaipmh/service/impl/InstancesServiceImplTest.java
src/test/java/org/folio/oaipmh/service/impl/SetServiceImplTest.java
src/test/java/org/folio/rest/impl/CleanUpJobTest.java
src/test/java/org/folio/rest/impl/ModTenantAPITest.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java
src/test/java/org/folio/rest/impl/OaiPmhSetImplTest.java

[MODOAIPMH-339](https://issues.folio.org/browse/MODOAIPMH-339) - Address memory leaks
Fix memory leaks in mod-oai-pmh module
Avoid creation vertx clients per each request, remove unused configurations from map.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication …

MODOAIPMH-339 - Address memory leaks

---

NEWS.md
pom.xml

[MODOAIPMH-346](https://issues.folio.org/browse/MODOAIPMH-346) - MODOAIPMH (mod-oai-pmh) release
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …

MODOAIPMH-346 - Release 3.6.0

---

src/main/java/org/folio/oaipmh/WebClientProvider.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java

[MODOAIPMH-374](https://issues.folio.org/browse/MODOAIPMH-374) - Fix memory issues for mod-oai-pmh module
Move logic to save and enrich instances to json parser handler from BatchStreamWrapper 
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …

MODOAIPMH-374 - Fix memory issues for mod-oai-pmh module

---

src/main/java/org/folio/oaipmh/WebClientProvider.java

[MODOAIPMH-374](https://issues.folio.org/browse/MODOAIPMH-374) - Fix memory issues for mod-oai-pmh module …

MODOAIPMH-339 - Fix memory issues for mod-oai-pmh module

---

src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java

[MODOAIPMH-374](https://issues.folio.org/browse/MODOAIPMH-374) - Fix memory issues for mod-oai-pmh module …

MODOAIPMH-374 -Fix memory issues for mod-oai-pmh module

---

NEWS.md
pom.xml
src/main/java/org/folio/oaipmh/WebClientProvider.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/main/resources/log4j2.properties

[MODOAIPMH-375](https://issues.folio.org/browse/MODOAIPMH-375) - MODOAIPMH (mod-oai-pmh) Bugfix release …

MODOAIPMH-375 - Release 3.6.1

---

NEWS.md
pom.xml

[MODOIAPMH-385](https://issues.folio.org/browse/MODOAIPMH-385) - MODOAIPMH (mod-oai-pmh) Kiwi Bugfix release

MODOIAPMH-385 - Release 3.6.2

---

NEWS.md
pom.xml

[MODAOIPMH-384](https://issues.folio.org/browse/MODOAIPMH-384) - MODOAIPMH (mod-oai-pmh) Juniper Hotfix release

MODAOIPMH-384 - Release 3.5.1

---

src/main/java/org/folio/oaipmh/dao/impl/InstancesDaoImpl.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/main/resources/liquibase/tenant/scripts/2020-07-16--10-00-create-instnace-ids-table.xml
src/test/java/org/folio/oaipmh/common/AbstractInstancesTest.java

[MODOAIPMH-378 ](https://issues.folio.org/browse/MODOAIPMH-378) - Change the way of saving instances ids for reducing the database load
Remove unused field from instances table 
- Are the JIRAs under active development?  
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …

MODOAIPMH-378 - Change the way of saving instances ids for reducing the database load

---

pom.xml
src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java
src/main/java/org/folio/oaipmh/mappers/MarcXmlMapper.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/main/java/org/folio/oaipmh/service/MetricsCollectingService.java
src/main/java/org/folio/oaipmh/service/SourceStorageSourceRecordsClientWrapper.java
src/main/java/org/folio/oaipmh/service/impl/InstancesServiceImpl.java
src/test/java/org/folio/oaipmh/service/impl/MetricsCollectingServiceTest.java

[MODOAIPMH-377](https://issues.folio.org/browse/MODOAIPMH-377) - Implement metrics for mod-oai-pmh

MODOAIPMH-377 - Implement metrics for mod-oai-pmh

---

src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java
src/test/java/org/folio/rest/impl/OkapiMockServer.java

[MODOAIPMH-392](https://issues.folio.org/browse/MODOAIPMH-392) - mod-oai-pmh master-branch build failure

MODOAIPMH-392 - mod-oai-pmh master-branch build failure

---

src/main/java/org/folio/oaipmh/processors/JsonParserErrorResolver.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/main/java/org/folio/oaipmh/processors/OaiPmhJsonParser.java
src/test/java/org/folio/oaipmh/processors/JsonParserErrorResolverTest.java
src/test/java/org/folio/oaipmh/processors/OaiPmhJsonParserTest.java

[MODOAIPMH-391](https://issues.folio.org/browse/MODOAIPMH-391) - Spike: Unexpected character error
Extend JsonParserImpl logic to add invalid json part logging.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …

MODOAIPMH-391 - Spike: Unexpected character error

---

pom.xml

[MODOAIPMH-399](https://issues.folio.org/browse/MODOAIPMH-399) - Update to log4j, RMB, Vert.x, postgresql
Updated:
log4j -> 2.17.2
postgres -> 42.3.3

MODOAIPMH-377 - Update to log4j, RMB, Vert.x, postgresql

---

NEWS.md
pom.xml

[MODOAIPMH-401](https://issues.folio.org/browse/MODOAIPMH-401) - MODOAIPMH (mod-oai-pmh) Lotus BF release …

MODOAIPMH-401 -  Release 3.7.1

---

src/main/java/org/folio/oaipmh/dao/InstancesDao.java
src/main/java/org/folio/oaipmh/dao/impl/InstancesDaoImpl.java
src/main/java/org/folio/oaipmh/domain/StatisticsHolder.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/main/java/org/folio/oaipmh/service/InstancesService.java
src/main/java/org/folio/oaipmh/service/impl/InstancesServiceImpl.java
src/main/resources/liquibase/tenant/changelog.xml
src/main/resources/liquibase/tenant/scripts/2022-04-12--18-00-update-request-metadata-table.xml
src/test/java/org/folio/oaipmh/service/impl/InstancesServiceImplTest.java

[MODOAIPMH-408](https://issues.folio.org/browse/MODOAIPMH-408) - Include mod-oai-pmh statistics for requests

MODOAIPMH-408 - mod-oai-pmh instances statistics

---

descriptors/ModuleDescriptor-template.json
ramls/examples/requestMetadata.sample
ramls/examples/requestMetadataCollection.sample
ramls/request-metadata.raml
ramls/schemas/dto/requestMetadata.json
ramls/schemas/dto/requestMetadataCollection.json
src/main/java/org/folio/oaipmh/dao/InstancesDao.java
src/main/java/org/folio/oaipmh/dao/impl/InstancesDaoImpl.java
src/main/java/org/folio/oaipmh/service/InstancesService.java
src/main/java/org/folio/oaipmh/service/impl/InstancesServiceImpl.java
src/main/java/org/folio/rest/impl/RequestMetadataAPIs.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java

[MODOAIPMH-412](https://issues.folio.org/browse/MODOAIPMH-412) - API for harvesting statistics

MODOIAPMH-412 - API for harvesting statistics

---

descriptors/ModuleDescriptor-template.json
ramls/request-metadata.raml
ramls/schemas/dto/requestMetadata.json
src/main/java/org/folio/oaipmh/dao/impl/InstancesDaoImpl.java
src/main/java/org/folio/oaipmh/domain/StatisticsHolder.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/main/resources/liquibase/tenant/changelog.xml
src/main/resources/liquibase/tenant/scripts/2022-05-12--15-00-add-saved-instances-counter-request-metadata-table.xml
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java

[MODOAIPMH-419](https://issues.folio.org/browse/MODOAIPMH-419)  Harvesting statistics API: stored instances statistics

MODOAIPMH-419 - Harvesting statistics API: stored instances statistics

---

src/main/java/org/folio/oaipmh/dao/impl/InstancesDaoImpl.java
src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/main/resources/liquibase/tenant/scripts/2022-05-18--16-00-add-extended-statistics-tables.xml

Follow-up PR to [#261](https://github.com/folio-org/mod-oai-pmh/pull/261) with refactoring and stability improvements.

MODOAIPMH-420 - Save UUIDs of failed instances

---

NEWS.md
pom.xml

[MODOAIPMH-415](https://issues.folio.org/browse/MODOAIPMH-415) - Release 3.8.0 (bump up artifact version in master)

MODOAIPMH-415 - Release 3.8.0 (bump up artifact version in master)

---

NEWS.md
README.md
descriptors/ModuleDescriptor-template.json
pom.xml
ramls/examples/requestMetadata.sample
ramls/examples/requestMetadataCollection.sample
ramls/examples/uuidCollection.sample
ramls/request-metadata.raml
ramls/schemas/dto/requestMetadata.json
ramls/schemas/dto/requestMetadataCollection.json
ramls/schemas/dto/uuidCollection.json
src/main/java/org/folio/oaipmh/dao/InstancesDao.java
src/main/java/org/folio/oaipmh/dao/impl/InstancesDaoImpl.java
src/main/java/org/folio/oaipmh/domain/StatisticsHolder.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/main/java/org/folio/oaipmh/service/InstancesService.java
src/main/java/org/folio/oaipmh/service/impl/InstancesServiceImpl.java
src/main/java/org/folio/rest/impl/RequestMetadataAPIs.java
src/main/resources/liquibase/tenant/changelog.xml
src/main/resources/liquibase/tenant/scripts/2022-04-12--18-00-update-request-metadata-table.xml
src/main/resources/liquibase/tenant/scripts/2022-05-12--15-00-add-saved-instances-counter-request-metadata-table.xml
src/main/resources/liquibase/tenant/scripts/2022-05-18--16-00-add-extended-statistics-tables.xml
src/test/java/org/folio/oaipmh/service/impl/InstancesServiceImplTest.java
src/test/java/org/folio/rest/impl/ModTenantAPITest.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java

[MODOAIPMH-415](https://issues.folio.org/browse/MODOAIPMH-415) - Release 3.8.0

MODOAIPMH-415 - Release 3.8.0

---

pom.xml

[MODOAIPMH-425](https://issues.folio.org/browse/MODOAIPMH-425) - RMB v34 upgrade - Morning Glory 2022 R2 module release

MODOAIPMH-425 - RMB v34 upgrade - Morning Glory 2022 R2 module release

---

NEWS.md
pom.xml
src/main/java/org/folio/oaipmh/helpers/records/RecordMetadataManager.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java

[MODOAIPMH-439](https://issues.folio.org/browse/MODOAIPMH-439) - MODOAIPMH (mod-oai-pmh) MG BF release

MODOAIPMH-439 - Release 3.9.1

---

PERSONAL_DATA_DISCLOSURE.md

[MODOAIPMH-437](https://issues.folio.org/browse/MODOAIPMH-437) - Add personal data disclosure form

MODOAIPMH-437 - Add personal data disclosure form

---

pom.xml
src/main/java/org/folio/rest/impl/InitAPIs.java
src/test/java/org/folio/oaipmh/helpers/RepositoryConfigurationUtilTest.java
src/test/java/org/folio/oaipmh/service/impl/SetServiceImplTest.java

[MODOAIPMH-446](https://issues.folio.org/browse/MODOAIPMH-446) - mod-oai-pmh: Upgrade RAML Module Builder …

MODOAIPMH-446 - mod-oai-pmh: Upgrade RAML Module Builder

---

NEWS.md
pom.xml

[MODOAIPMH-429](https://issues.folio.org/browse/MODOAIPMH-429) - MODOAIPMH (mod-oai-pmh) Nolana release

MODOAIPMH-429 - Release 3.10.0

---

README.md
src/main/java/org/folio/oaipmh/Constants.java
src/main/java/org/folio/oaipmh/mappers/PropertyNameMapper.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/main/resources/config/technical.json
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java
src/test/resources/config/technical.json

[MODOAIPMH-422](https://issues.folio.org/browse/MODOAIPMH-422) - Make DATABASE_FETCHING_CHUNK_SIZE configurable in the Configuration
DATABASE_FETCHING_CHUNK_SIZE is hardcoded in the mod-oai-pmh. For the investigations and performance tuning this value should be configurable.
Ideally all of the PRs involved in breaking changes would be merged in the same …

MODOAIPMH-422 - Make DATABASE_FETCHING_CHUNK_SIZE configurable in the Configuration

---

PULL_REQUEST_TEMPLATE.md
src/main/resources/log4j2-json.properties
src/main/resources/log4j2.properties

[MODOAIPMH-453](https://issues.folio.org/browse/MODOAIPMH-453) - Logging improvement - Configuration
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …

MODOAIPMH-453 - Logging improvement - Configuration

---

src/main/java/org/folio/oaipmh/Constants.java

[MODOAIPMH-434](https://issues.folio.org/browse/MODOAIPMH-434) - Correct verbiage of error message
The verbiage of the error message that is returned when there are no records returned.  This error occurs mostly during incremental harvests when the query might not find any matching records.
Corrected the error verbiage
Ideally all of the PRs involved in …

MODOAIPMH-434 - Correct verbiage of error message

---

src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java

[MODOAIPMH-475](https://issues.folio.org/browse/MODOAIPMH-475) - Increase max event loop execute time
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …

MODOAIPMH-475 - increase max event loop execute time

---

src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java
src/test/resources/inventory_view/enriched_instance.json

[MODOAIPMH-469](https://issues.folio.org/browse/MODOAIPMH-469) - Missing Call number data from harvested holdings record
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …

MODOAIPMH-469 - Missing Call number data from harvested holdings record

---

NEWS.md
pom.xml
src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java

[MODOAIPMH-476](https://issues.folio.org/browse/MODOAIPMH-476) - mod-oai-pmh: module release

Release 3.11.0

---

src/main/java/org/folio/oaipmh/Constants.java
src/main/java/org/folio/oaipmh/Request.java
src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java
src/main/java/org/folio/oaipmh/helpers/AbstractHelper.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java

[MODOAIPMH-487](https://issues.folio.org/browse/MODOAIPMH-487) - OAI-PMH returns more records than Max Records settings when Record source = SRS + Inventory
Fix cursor resetting when switching to Inventory once SRS exhausted.
Introduce new field in Request to store old cursor value.
Ideally all of the PRs involved in breaking changes would be merged in the …

MODOAIPMH-487 - OAI-PMH returns more records than Max Records settings when Record source = SRS + Inventory

---

src/main/java/org/folio/oaipmh/Constants.java
src/main/java/org/folio/oaipmh/Request.java
src/main/java/org/folio/oaipmh/dao/InstancesDao.java
src/main/java/org/folio/oaipmh/dao/impl/InstancesDaoImpl.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/main/java/org/folio/oaipmh/service/InstancesService.java
src/main/java/org/folio/oaipmh/service/impl/InstancesServiceImpl.java
src/main/java/org/folio/rest/impl/OaiPmhImpl.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java
src/test/java/org/folio/rest/impl/OkapiMockServer.java
src/test/resources/inventory_view/list_identifiers_folio_and_marc_view_20.json

[MODOAIPMH-482](https://issues.folio.org/browse/MODOAIPMH-482) - Added Item record to Instance FOLIO with Holdings FOLIO not included with verb ListIdentifiers
Harvest records with verb=ListIdentifiers once editing/adding holdings or items.
Move ListIdentifiers with marc21_withholdings to MarcWithHoldingsRequestHelper.
Ideally all of the PRs involved in …

MODOAIPMH-482 - Added Item record to Instance FOLIO with Holdings FOLIO not included with verb ListIdentifiers

---

src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java
src/main/java/org/folio/oaipmh/helpers/GetOaiRecordHelper.java
src/main/java/org/folio/oaipmh/helpers/GetOaiRepositoryInfoHelper.java
src/main/java/org/folio/oaipmh/helpers/GetOaiSetsHelper.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/main/java/org/folio/rest/impl/OaiPmhImpl.java
src/main/java/org/folio/rest/impl/OaiPmhSetImpl.java

TD: set error debug level for errors instead of warn.

TD: Logging improvement: warn2error

---

README.md

Updating README file with actual memory settings

README update: memory settings

---

src/main/java/org/folio/oaipmh/dao/InstancesDao.java
src/main/java/org/folio/oaipmh/dao/impl/InstancesDaoImpl.java
src/main/java/org/folio/oaipmh/helpers/AbstractHelper.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/main/java/org/folio/oaipmh/service/InstancesService.java
src/main/java/org/folio/oaipmh/service/impl/InstancesServiceImpl.java
src/test/java/org/folio/oaipmh/service/impl/InstancesServiceImplTest.java
src/test/java/org/folio/rest/impl/CleanUpJobTest.java
src/test/java/org/folio/rest/impl/InventoryUpdatedInstanceIds.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java
src/test/java/org/folio/rest/impl/OkapiMockServer.java

[MODOAIPMH-506](https://issues.folio.org/browse/MODOAIPMH-506) - /inventory-hierarchy : source-parameter supporting
/inventory-hierarchy : source-parameter supporting to download only instances with fixed source …

MODOAIPMH-506 - /inventory-hierarchy : source-parameter supporting

---

src/main/java/org/folio/oaipmh/dao/PostgresClientFactory.java
src/main/java/org/folio/oaipmh/dao/impl/InstancesDaoImpl.java
src/main/java/org/folio/oaipmh/dao/impl/SetDaoImpl.java

[MODOAIPMH-457](https://issues.folio.org/browse/MODOAIPMH-457) - PoC for moving to RMB approach
Based on results of spike [MODOAIPMH-456](https://issues.folio.org/browse/MODOAIPMH-456) the RMB-based approach was chosen - Moving to RMB approach. PoC for this approach should be implemented.
Implemented logic to split read/write operations
Ideally all of the …

MODOAIPMH-457 - PoC for moving to RMB approach

---

src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java
src/test/java/org/folio/rest/impl/OkapiMockServer.java
src/test/resources/inventory_view/instance_id_invalid_call_number_type_enriched_instance.json

[MODOAIPMH-442](https://issues.folio.org/browse/MODOAIPMH-442) - bad data in call number type field returns 500 error
Handle case when call number type id has invalid value (not UUID), log error and continue harvesting.
Remove promise.fail after 500 response from /inventory-hierarchy/items-and-holdings. In case of error, entire batch of instances will not be enriched.
- Do PRs exist for …

MODOAIPMH-442 - bad data in call number type field returns 500 error

---

src/main/java/org/folio/oaipmh/helpers/records/RecordMetadataManager.java
src/test/java/org/folio/oaipmh/helpers/records/RecordMetadataManagerTest.java
src/test/resources/metadata-manager/electronic_access-component_parts_of_resource.json
src/test/resources/metadata-manager/electronic_access-version_of_component_parts_of_resource.json

[MODOAIPMH-477](https://issues.folio.org/browse/MODOAIPMH-477) - Adjust 856 mappings
While …

MODOAIPMH-477 - update 856 with new types of relationship

---

src/main/resources/rules/rulesDefault.json

[MODOAIPMH-477](https://issues.folio.org/browse/MODOAIPMH-477) - Adjust 856 mappings
While …

MODOAIPMH-477 - update 856 json rules

---

src/main/java/org/folio/oaipmh/processors/JsonWriter.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/test/java/org/folio/oaipmh/service/impl/MetricsCollectingServiceTest.java
src/test/resources/log4j2.properties

Follow-up PR to [PR#316](https://github.com/folio-org/mod-oai-pmh/pull/316) with utilization tracker improvement.
Fix occasionally OOMs during full harvesting (marc21_withholdings).
Logic for utilization tracker is re-worked. …

MODOAIPMH-509 - [Orchid] [OAI-PMH] Full harvesting - OutOfMemory Exception

---

src/main/java/org/folio/oaipmh/Request.java
src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java
src/main/java/org/folio/oaipmh/helpers/AbstractHelper.java
src/main/java/org/folio/oaipmh/helpers/GetOaiRecordHelper.java
src/main/java/org/folio/oaipmh/helpers/RepositoryConfigurationUtil.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/main/java/org/folio/rest/impl/OaiPmhImpl.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java

[MODOAIPMH-499](https://issues.folio.org/browse/MODOAIPMH-499) - mod-oai-pmh returns 500 error when depended module reboots
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …

MODOAIPMH-499 - mod-oai-pmh returns 500 error when depended module reboots

---

src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java
src/main/java/org/folio/oaipmh/helpers/records/RecordMetadataManager.java
src/test/java/org/folio/oaipmh/helpers/records/RecordMetadataManagerTest.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java
src/test/resources/metadata-manager/srs_instance_with_two_electronic_accesses.json

[MODOAIPMH-507](https://issues.folio.org/browse/MODOAIPMH-507) - 856 field subfield "t" is not returned in response for Instance with electronic access in some cases
Instance with electronic access fields should be included in response with subfield "t" set to "0" in each electronic access type 856 field
* Fixed metadata update logic
* Updated unit tests …

MODOAIPMH-507 - 856 field subfield "t" is not returned in response for Instance with electronic access in some cases

---

src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java

[MODOAIPMH-519](https://issues.folio.org/browse/MODOAIPMH-519) - SRS records which are not marked as "deleted" are omitted in response with "Deleted records support" set to "NO"
SRS records with "05" position of "LDR" field set to a/c/n/p are omitted in response with settings: "Deleted records support" set to "NO" for verbs: verb=GetRecord (metadataPrefix=marc21and marc21_withholdings), verb=ListRecords (marc21), verb=ListIdentifiers (marc21)
Both for "Record source" set to "SRS" and "SRS+Inventory"
Fixed request parameters
- …

MODOAIPMH-519 - SRS records which are not marked as "deleted" are omitted in response with "Deleted records support" set to "NO"

---

Dockerfile
Jenkinsfile
pom.xml
src/main/java/org/folio/oaipmh/ResponseConverter.java

[MODOAIPMH-525](https://issues.folio.org/browse/MODOAIPMH-525) - Update to Java 17 mod-oai-pmh
Update the module to Java 17 and identify issues.
Module updated to Java 17
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …

MODOAIPMH-525 - Update to Java 17 mod-oai-pmh

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/oaipmh/processors/GetListRecordsRequestHelper.java

[MODOAIPMH-524](https://issues.folio.org/browse/MODOAIPMH-524) - SRS-client with "shared" MARC records support
Modify shared source name.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …

MODOAIPMH-524 - SRS-client with "shared" MARC records support

---

src/main/java/org/folio/oaipmh/helpers/records/RecordMetadataManager.java
src/test/java/org/folio/oaipmh/helpers/records/RecordMetadataManagerTest.java

[MODOAIPMH-533](https://issues.folio.org/browse/MODOAIPMH-533) - Add missing electronic access relationship value to default rules
* minor improvements
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …

MODOAIPMH-533 - Add missing electronic access relationship value to default rules

---

NEWS.md
pom.xml

[MODOAIPMH-538](https://issues.folio.org/browse/MODOAIPMH-538) - mod-oai-pmh: module release
Release v3.12.0 …

MODOAIPMH-538 - mod-oai-pmh: module release

---

NEWS.md
pom.xml

[MODOAIPMH-544](https://issues.folio.org/browse/MODOAIPMH-544) - mod-oai-pmh: module release

Release 3.12.1

---

NEWS.md
pom.xml

Release 3.12.2

---

NEWS.md
pom.xml

Release 3.12.3

---

pom.xml

MODOAIPMH-544 bump up folio-s3-client

---

NEWS.md
pom.xml

Release 3.12.4

---

src/main/java/org/folio/oaipmh/helpers/storage/RecordStorageHelper.java

[MODOAIPMH-546](https://issues.folio.org/browse/MODOAIPMH-546) - ECS: ListRecords returns suppressed from discovery Shared MARC Instance with flag t=0 in 999 and 856 fields
Suppressed from discovery shared MARC Instance is returned with flag t=0 in 999 and 856 fields when harvesting with ListRecords (incremental harvesting, full harvesting).
Use value from inventory if srs is null.
- Do …

MODOAIPMH-546 - ECS: ListRecords returns suppressed from discovery Shared MARC Instance with flag t=0 in 999 and 856 fields

---

NEWS.md
pom.xml

[MODOAIPMH-547](https://issues.folio.org/browse/MODOAIPMH-547) - mod-oai-pmh: module release
Release v3.12.7. …

Release 3.12.7

---

NEWS.md
pom.xml
src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java

[MODOAIPMH-551](https://issues.folio.org/browse/MODOAIPMH-551) - mod-oai-pmh: module release

Release 3.12.8

---

pom.xml
src/main/java/org/folio/oaipmh/dao/impl/ErrorsDaoImpl.java
src/main/java/org/folio/oaipmh/dao/impl/InstancesDaoImpl.java

[MODOAIPMH-559](https://folio-org.atlassian.net/browse/MODOAIPMH-559) - mod-oai-pmh: Upgrade RAML Module Builder
Update RMB version.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …

MODOAIPMH-559 - mod-oai-pmh: Upgrade RAML Module Builder

---

NEWS.md
pom.xml
ramls/schemas/OAI-PMH.xsd
src/main/java/org/folio/oaipmh/Constants.java
src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java
src/main/java/org/folio/oaipmh/helpers/AbstractHelper.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java
src/test/java/org/folio/rest/impl/OkapiMockServer.java
src/test/resources/source-storage/source-records/instances_1_with_invalid_character.json

Release 3.13.1

---

descriptors/ModuleDescriptor-template.json
ramls/request-metadata.raml
src/main/java/org/folio/oaipmh/dao/impl/InstancesDaoImpl.java
src/main/java/org/folio/rest/impl/RequestMetadataAPIs.java
src/test/java/org/folio/oaipmh/service/impl/ErrorsServiceImplTest.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java

[MODOAIPMH-553](https://folio-org.atlassian.net/browse/MODOAIPMH-553) - Request has expired error on downloading error logs
The token expiration while downloading files from S3 - the behavior should be consistent with the link to the data generated by data-export.
* Introduced new endpoint for download
* Implemented new logic
* Updated unit tests
Ideally …

MODOAIPMH-553 - Request has expired error on downloading error logs

---

src/main/resources/xslt/MARC21slim2OAIDC.xsl

[MODOAIPMH-550](https://folio-org.atlassian.net/browse/MODOAIPMH-550) - Harvesting FOLIO Instances with oai_dc metadataPrefix returns "text" in <dc:type> regardless the Instance resource type
FOLIO Instances of different resource types (e.g. text; two-dimensional moving image; performed music; three-dimensional form; computer program; other) when harvested with oai_dc metadataPrefix include "text" in <dc:type> regardless the Instance resource type
Fixed OAI_DC mapper
- Do JIRAs …

MODOAIPMH-550 - Harvesting FOLIO Instances with oai_dc metadataPrefix returns "text" in <dc:type> regardless the Instance resource type

---

src/main/java/org/folio/oaipmh/processors/OaiPmhJsonParser.java
src/test/java/org/folio/oaipmh/processors/OaiPmhJsonParserTest.java

[MODOAIPMH-565](https://folio-org.atlassian.net/browse/MODOAIPMH-565) - Skip invalid instance records when inventory responds with 500
If issue happens calling POST /inventory-hierarchy/items-and-holdings parsing fails. Error should be caught and such instance is logged.
Parser is updated to handle not only DecodeException.
Ideally all of the PRs involved …

MODOAIPMH-565 - Skip invalid instance records when inventory responds with 500

---

src/main/java/org/folio/oaipmh/ResponseConverter.java
src/test/java/org/folio/oaipmh/ResponseConverterTest.java

[MODOAIPMH-556](https://folio-org.atlassian.net/browse/MODOAIPMH-556) - Improve clarity of the error message
Harvest errors should provide enough information to troubleshoot the issue.
* Improved clarity of error message …

MODOAIPMH-556 - Improve clarity of the error message

---

NEWS.md
pom.xml
src/main/java/org/folio/oaipmh/processors/OaiPmhJsonParser.java
src/test/java/org/folio/oaipmh/processors/OaiPmhJsonParserTest.java

[MODOAIPMH-569](https://folio-org.atlassian.net/browse/MODOAIPMH-569)  - Release 3.13.2

MODOAIPMH-569 - Release 3.13.2

---

descriptors/ModuleDescriptor-template.json

MODOAIPMH-575 API version update

---

NEWS.md
pom.xml
src/main/java/org/folio/oaipmh/processors/RuleProcessor.java

Release v3.14.0.
While it's helpful for reviewers to help identify potential problems, …

FOLIO-4101 - Release 3.14.0

---

NEWS.md
pom.xml

Release v3.14.1.
Increase aws sdk version.
While it's helpful for reviewers to help identify …

FOLIO-4101 - Release 3.14.1

---

descriptors/ModuleDescriptor-template.json

MODOAIPMH-585 Missing interface dependencies in module descriptor

---

src/main/java/org/folio/oaipmh/exception/BuildOaiMetadataException.java
src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java

[MODOAIPMH-567](https://folio-org.atlassian.net/browse/MODOAIPMH-567) - GetRecord unexpectedly returns "invalidRecordContent" error for deleted MARC Instance
Return correct error code when instance marked is as deleted.
Rework approach implemented in https://folio-org.atlassian.net/browse/MODOAIPMH-540
Ideally all of the PRs involved in breaking changes …

MODOAIPMH-567 - GetRecord unexpectedly returns "invalidRecordContent" error for deleted MARC Instance

---

README.md
descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/oaipmh/mappers/MarcXmlMapper.java

[MODOAIPMH-584](https://folio-org.atlassian.net/browse/MODOAIPMH-584) - Character encoding inconsistent for non-ASCII location names in OAI-PMH 952 holdings
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …

MODOAIPMH-584 - Character encoding inconsistent for non-ASCII location names in OAI-PMH 952 holdings

---

NEWS.md
pom.xml

[FOLIO-4101](https://folio-org.atlassian.net/browse/FOLIO-4101) - Release 3.14.2

FOLIO-4101 - Release 3.14.2

---

NEWS.md
pom.xml

Release 3.14.3 

---

Dockerfile
Jenkinsfile
pom.xml

[MODOAIPMH-594](https://folio-org.atlassian.net/browse/MODOAIPMH-594) - Update to mod-oai-pmh Java 21
Java version updating
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …

MODOAIPMH-594 - Update to mod-oai-pmh Java 21

---

pom.xml

MODOAIPMH-594 bump up aws sdk version

---

pom.xml

MODOAIPMH-594 add json path dependency

---

NEWS.md
pom.xml

[MODOAIPMH-608](https://folio-org.atlassian.net/browse/MODOAIPMH-608) - Release 3.15.0

MODOAIPMH-608 - Release 3.15.0

---

pom.xml

[MODOAIPMH-611](https://folio-org.atlassian.net/browse/MODOAIPMH-611) - Update dependencies for Sunflower fixing vulns
Reverting unnecessary dependencies from [PR#402](https://github.com/folio-org/mod-oai-pmh/pull/402). …

MODOAIPMH-611 - Update dependencies for Sunflower fixing vulns (revert unnecessary dependencies)

---

NEWS.md
pom.xml
src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java
src/main/java/org/folio/oaipmh/processors/GetListRecordsRequestHelper.java
src/main/java/org/folio/oaipmh/service/SourceStorageSourceRecordsClientWrapper.java
src/test/java/org/folio/rest/impl/ModTenantAPIIT.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java

[MODOAIPMH-616](https://folio-org.atlassian.net/browse/MODOAIPMH-616) - Release 3.15.1
While …

MODOAIPMH-616 - Release 3.15.1

---

src/main/java/org/folio/oaipmh/querybuilder/QueryBuilder.java

[MODOAIPMH-613](https://folio-org.atlassian.net/browse/MODOAIPMH-613) - Set for deletion MARC Instances are not harvested with ListRecords, ListIdentifiers requests
Deleted in the following ways MARC Instances are not harvested with ListRecords, ListIdentifiers requests.
Since audit table is no longer used for deletion, created_date, which was used in audit table, is not actual anymore and updated_date of instance should be used instead.
- Do JIRAs exist to update the impacted …

MODOAIPMH-613 - Set for deletion MARC Instances are not harvested with ListRecords, ListIdentifiers requests

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/oaipmh/querybuilder/QueryBuilder.java
src/main/resources/templates/db_scripts/schema.json
src/main/resources/templates/db_scripts/update_instance_deleted.sql

Release 3.15.2

---

src/main/java/org/folio/oaipmh/helpers/records/RecordMetadataManager.java
src/test/java/org/folio/oaipmh/helpers/records/RecordMetadataManagerTest.java

https://folio-org.atlassian.net/browse/MODOAIPMH-561?atlOrigin=eyJpIjoiZjVmYjI3MjBjZGY1NGExNGI2ZGI2NGY4Njk2ZGE0MzMiLCJwIjoiaiJ9

MODOAIPMH-561: Adding inactive prefix to effective locations

---

src/main/resources/templates/db_scripts/add_null_check_for_deleted.sql
src/main/resources/templates/db_scripts/schema.json
src/main/resources/templates/db_scripts/update_instance_deleted.sql
src/test/resources/sql/init_database_for_oaiPmhImplTest.sql
src/test/resources/sql/init_database_with_data.sql

[MODOAIPMH-624](https://folio-org.atlassian.net/browse/MODOAIPMH-624) - Add check for possible absence of instance.jsonb.deleted
Field {tenant_id}_mod_inventory_storage.instance jsonb deleted field is not always present, so need to check for possible null additionally, otherwise such records without ‘deleted’ field are not included in the response.
Update view.
- Do PRs exist for these …

MODOAIPMH-624 -  Add check for possible absence of instance.jsonb.deleted

---

NEWS.md
pom.xml
src/main/resources/templates/db_scripts/add_null_check_for_deleted.sql
src/main/resources/templates/db_scripts/schema.json
src/test/resources/sql/init_database_for_oaiPmhImplTest.sql
src/test/resources/sql/init_database_with_data.sql

Release v3.15.3.
Release v3.15.3
While it's helpful for reviewers to help identify potential …

Release v3.15.3 (Sunflower)

---

src/main/resources/templates/db_scripts/remove_audit_dependencies.sql
src/main/resources/templates/db_scripts/schema.json
src/test/resources/sql/init_database_for_oaiPmhImplTest.sql
src/test/resources/sql/init_database_with_data.sql

[MODOAIPMH-615](https://folio-org.atlassian.net/browse/MODOAIPMH-615) - Remove OAI-PMH dependency on instance_audit table
Remove audit dependencies.
Remove get_deleted_instances view.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …

MODOAIPMH-615 - Remove OAI-PMH dependency on instance_audit table
