folio-org/mod-oai-pmh

NEWS.md
README.md
pom.xml
ramls/schemas/MARC21slim.xsd
ramls/schemas/OAI-PMH.xsd
ramls/schemas/bindings.xjb
ramls/schemas/oai_dc.xsd
ramls/schemas/simpledc20021212.xsd

- OAI-PMH, DC and MARC21 schemas added
- jaxb plugin generates java classes from the schemas above

MODOAIPMH-6 Define schemas

---

pom.xml
ramls/oai-pmh.raml
ramls/schemas/bindings.xjb
ramls/traits/selective.raml
src/main/java/org/folio/oaipmh/ResponseHelper.java
src/main/java/org/folio/rest/impl/GetOaiRepositoryInfoHelper.java
src/main/java/org/folio/rest/impl/InitAPIs.java
src/main/java/org/folio/rest/impl/OaiPmhImpl.java
src/main/resources/config/config.properties
src/test/java/org/folio/oaipmh/ResponseHelperTest.java
src/test/java/org/folio/rest/impl/InitAPIsTest.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java
src/test/resources/config/config.properties

- The implementation of the Identify verb
- The rest of the verbs are implemented to return an error that the logic is not implemented yet
- Update raml so from/until parameters are defined as strings because if datetime is used, the parameters are passed to corresponding methods always null
- Modifying jaxb binding to use Instant as a date
- Adding maven-antrun-plugin to enable local html api console usage

MODOAIPMH-35 implement verb Identify

---

pom.xml
src/main/java/org/folio/oaipmh/ResponseHelper.java
src/main/java/org/folio/oaipmh/mappers/XSLTMapper.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java
src/test/java/org/folio/rest/impl/OkapiMockServer.java
src/test/resources/log4j2.properties

- pom.xml updates:
- Switching to RMB of `v23.1.0`
- Adding `httpclient`and `commons-lang3` dependencies instead of relying on transitive dependencies
- Unit test updates to verify different compressions
- Fixing issues highlighted by Sonar
- Disabling `squid:S1191` for `ResponseHelper` because `NamespacePrefixMapper` is used by jaxb
- Enabling `FEATURE_SECURE_PROCESSING` in `TransformerFactory` as suggested in `squid:S4435`

MODOAIPMH-53 OAI-PMH: Response Compression (backend module)

---

NEWS.md
README.md
src/main/java/org/folio/oaipmh/ResponseHelper.java
src/main/java/org/folio/oaipmh/helpers/storage/StorageHelper.java

- SRS is enabled by default
- The Readme updated with information about `repository.storage` system property usage
- Debug logging of the execution time for bytes to jaxb object transformation

MODOAIPMH-63 Enable SRS usage by default

---

Dockerfile
descriptors/ModuleDescriptor-template.json

Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).

MODOAIPMH-80 FOLIO-2358 manage container memory

---

ramls/oai-pmh.raml
ramls/rtypes/list.raml
ramls/traits/metadataPrefix.raml
ramls/traits/partitionable.raml
src/main/java/org/folio/oaipmh/helpers/GetOaiIdentifiersHelper.java
src/main/java/org/folio/oaipmh/helpers/GetOaiMetadataFormatsHelper.java
src/main/java/org/folio/oaipmh/helpers/GetOaiRecordHelper.java
src/main/java/org/folio/oaipmh/helpers/GetOaiRecordsHelper.java
src/main/java/org/folio/oaipmh/helpers/GetOaiRepositoryInfoHelper.java
src/main/java/org/folio/oaipmh/helpers/GetOaiSetsHelper.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java

According to the OAI-PMH spec, the text/xml MIME type must be supported.  To meet this requirement, I'm switching `application/xml` -> `text/xml`
See https://issues.folio.org/browse/MODOAIPMH-86
- **N.B.** this is a breaking change!

MODOAIPMH-86: Must support text/xml

---

pom.xml
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java
src/test/java/org/folio/rest/impl/OkapiMockServer.java

https://issues.folio.org/browse/MODOAIPMH-92
* migrated RMB to v29.3.0
* dependencies update
* removed content encoding tests since RMB v29 supports [compression by default](https://github.com/folio-org/raml-module-builder/blob/master/domain-models-runtime/src/main/java/org/folio/rest/RestVerticle.java#L318)

MODOAIPMH-92 - RMB 29.3.0 update

---

src/main/java/org/folio/oaipmh/MetadataPrefix.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java

Add new metadata format with name "marc21_withholdings". This format supported by the repository and use the same schema as marc21.
[https://issues.folio.org/browse/MODOAIPMH-141](url)

MODOAIPMH-141 Add marc21_withholdings to ListMetadataFormats

---

descriptors/ModuleDescriptor-template.json
ramls/oai-pmh.raml

Change version of oai-pmh in  ModuleDescriptor and raml files from 2.0 to 3.0. Remove permissions for unused endpoints.
[https://issues.folio.org/browse/MODOAIPMH-157](url)

MODOAIPMH-157 Preparation to MODOAIPMH release

---

src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java

As the until date filtering in inventory view is non-inclusive, we need to compensate the until date with either +1 second (if datetime) or +1 day in cases when date-only is supplied in from param.

Compensate until date with +1 sec/day for marc21_witholdings and verb=listrecords

---

descriptors/ModuleDescriptor-template.json

PURPOSE
environment variables have been added to module descriptor which fixes the issue with databse on bugfest environment..
Jira: https://issues.folio.org/browse/EDGOAIPMH-51

EDGOAIPMH-51: ListRecords with metdataPrefix=marc21_withholdings timeouts on BugFest

---

ramls/examples/filtering_condition_value_collection.sample
ramls/examples/folioSet.sample
src/main/java/org/folio/oaipmh/dao/impl/SetDaoImpl.java
src/main/resources/liquibase/tenant/changelog.xml
src/main/resources/liquibase/tenant/scripts/2020-08-28--11-00-add-unique-constraint-for-name-and-set_spec-columns.xml
src/test/java/org/folio/oaipmh/service/impl/SetServiceImplTest.java
src/test/java/org/folio/rest/impl/OaiPmhSetImplTest.java

Add unqiue constraints for both name and setSpec columns. 
Jira: https://issues.folio.org/browse/MODOAIPMH-220
**name unique validation**
**setSpec unique validation**

MODOAIPMH-220: Perform uniqueness validation for sets endpoints

---

src/main/java/org/folio/rest/impl/OaiPmhSetImpl.java
src/test/java/org/folio/rest/impl/OaiPmhSetImplTest.java

FIx issue with 500 error code responding instead of 422 with proper error message when try to save or update set with empty name or setSpec value.
Jira: https://issues.folio.org/browse/MODOAIPMH-206

MODOAIPMH-206: POST /oai-pmh/set returns 500 when empty string is passed

---

Dockerfile
pom.xml

Removed implicit docker API version det (used before to fix env issue). Updated RAML version.

MODOAIPMH-230: Reference environment builds broken 2020-09-16 -- mod-oai-pmh?

---

src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java
src/main/java/org/folio/oaipmh/helpers/AbstractHelper.java

Fix issue with incorrect number of records returning by listrecords with resumption token for both marc21 and marc21_withholdings metadata formats
Jira: https://issues.folio.org/browse/MODOAIPMH-216

MODOAIPMH-216: Incorrect number of records returned by listrecords with resumption token for marc21 and marc21_withholdings

---

descriptors/ModuleDescriptor-template.json

Fix Edge module doesn't return the data, even if mod-oai-pmh does
This happened because diku_admin has all the necessary permissions, but the instituitional user diku, which is used when requests go through edge-oai-pmh, does not. This will be resolved in mod-oai-pmh 's module-descriptor.
Jira: https://issues.folio.org/browse/MODOAIPMH-245

Add missing permission

---

pom.xml

RMB 31.1.3 contains:
* [RMB-740](https://issues.folio.org/browse/RMB-740) Use FOLIO fork of vertx-sql-client and vertx-pg-client with
the following two patches
* [RMB-739](https://issues.folio.org/browse/RMB-739) Make RMB's DB\_CONNECTIONRELEASEDELAY work again, defaults to 60 seconds
* [FOLIO-2840](https://issues.folio.org/browse/FOLIO-2840) Fix duplicate names causing 'prepared statement "XYZ" already exists'
* [RMB-738](https://issues.folio.org/browse/RMB-738) Upgrade to Vert.x 3.9.4, most notable fix: RowStream fetch
can close prematurely the stream https://github.com/eclipse-vertx/vertx-sql-client/issues/778

MODOAIPMH-249: Upgrade to RMB 31.1.3, Vert.x 3.9.4

---

NEWS.md
pom.xml

* [MODOAIPMH-248](https://issues.folio.org/browse/MODOAIPMH-248) Upgrade RMB to 30.2.9:
* [RMB-740](https://issues.folio.org/browse/RMB-740) Use FOLIO fork of vertx-sql-client and vertx-pg-client with
the following two patches
* [RMB-739](https://issues.folio.org/browse/RMB-739) Make RMB's DB\_CONNECTIONRELEASEDELAY work again, defaults to 60 seconds
* [FOLIO-2840](https://issues.folio.org/browse/FOLIO-2840) Fix duplicate names causing 'prepared statement "XYZ" already exists'
* [RMB-738](https://issues.folio.org/browse/RMB-738) Upgrade to Vert.x 3.9.4, most notable fix: RowStream fetch
can close prematurely the stream https://github.com/eclipse-vertx/vertx-sql-client/issues/778

MODOAIPMH-248: Release 3.1.3 with RMB 30.2.9, Vert.x 3.9.4

---

src/main/java/org/folio/oaipmh/helpers/GetOaiIdentifiersHelper.java

Fix issue with incorrect number of items being returned when perform ListIdentifiers request.
_Cannot be covered with unit tests cause number of returned records are mocked. 
Test coverage will be added in Karate integration test project._ 
Jira: https://issues.folio.org/browse/MODOAIPMH-250

MODOAIPMH-250 Invalid number of identifiers are returned when get ListIdentifiers

---

NEWS.md
README.md
pom.xml

Release the mod-oai-pmh v3.2.4 which contains bug fixes for processing marc21_withholdings metadata format.
Jira: https://issues.folio.org/browse/MODOAIPMH-253

MODOAIPMH-253: mod-oai-pmh-3.2.4- Honeysuckle Bugfix release

---

src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java
src/main/java/org/folio/oaipmh/helpers/AbstractHelper.java
src/main/java/org/folio/oaipmh/helpers/GetOaiIdentifiersHelper.java
src/main/java/org/folio/oaipmh/helpers/GetOaiMetadataFormatsHelper.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java

Jira: https://issues.folio.org/browse/MODOAIPMH-240
Resolve conflicts between time zones when running tests locally plus fixing by these changes the bug related to records requesting with invalid time borders.
The SRS client converts the date to UTC therefore the end date will be as next: passed date param - time differnce between env system time zone(STZ) and UTC.
Before passing the dates to SRC client we add the time diff between current system time zone and UTC and further the same time diff will be subtracted by the SRC client back and by the end the same date which has been passed as param will be used as search criteria for records.
Example how it worked before: 
- STZ is +02:00
- before param which is passed equals to 2018-12-12T00:00:00z
- SRC client under the hood converts the …

MODOAIPMH-240: Newest git update introduces build loop

---

ramls/schemas/OAI-PMH.xsd
src/main/java/org/folio/oaipmh/Constants.java
src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java
src/main/java/org/folio/oaipmh/helpers/AbstractHelper.java
src/main/java/org/folio/oaipmh/helpers/storage/AbstractStorageHelper.java
src/main/java/org/folio/oaipmh/helpers/storage/StorageHelper.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java

Jira: https://issues.folio.org/browse/MODOAIPMH-123
Make header datestamps be affected by time granularity setting, i.e. header datestamp should match time granularity format.
Set date to header type in a particular date format.

MODOAIPMH-123: Datestamp in response doesn't correspond to time granularity

---

src/main/resources/liquibase/tenant/scripts/2020-11-19--18-00-create-request-metadata-table.xml

Jira: https://issues.folio.org/browse/MODOAIPMH-271
Enrich request_metadata_lb with request_ids, which are absent within instances table, and last_updated_date as current date.

MODOAIPMH-271: Create a database migration script to enrich new oai-pmh tables.

---

pom.xml

mod-oai-pmh was already at 3.3.0 initially, reference environments already are at 3.3.0-SNAPSHOT. For them to pick up the pom.xml has to be greater than or equal to 3.3.0 .

Updating to 3.3.0 version

---

src/main/java/org/folio/oaipmh/dao/InstancesDao.java
src/main/java/org/folio/oaipmh/dao/impl/InstancesDaoImpl.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/main/java/org/folio/oaipmh/service/InstancesService.java
src/main/java/org/folio/oaipmh/service/impl/InstancesServiceImpl.java
src/test/java/org/folio/oaipmh/common/AbstractInstancesTest.java
src/test/java/org/folio/oaipmh/service/impl/InstancesServiceImplTest.java
src/test/java/org/folio/rest/impl/CleanUpJobTest.java

Jira: https://issues.folio.org/browse/MODOAIPMH-274
When there are several initial-loads runs simultaneously, then when the first of them will finish then it is going to pick up the first batch of instance ids without considering the current request-id which will lead to retrieving mixed instance ids which can relate to different request ids(harvesters) or duplicated ids by the reason that it can retrieve the same instance ids which hold different request ids, such duplicates lead to an error.
Add request id as param for both getInstances and deleteInstances methods.

MODOAIPMH-274: Retrieving loaded instance ids doesn't take the request id into account.

---

NEWS.md
pom.xml

Jira: https://issues.folio.org/browse/MODOAIPMH-272
Release the module. As well the 3.3.0 version of the next development iteration specified since there the same version was accidentally deployed to testing/snapshot environments and we should keep the same version within pom in order to have the latest changes being redeployed at environments.

MODOAIPMH-272: Release the mod-oai-pmh v3.2.5

---

src/main/java/org/folio/oaipmh/dao/PostgresClientFactory.java
src/test/java/org/folio/oaipmh/common/AbstractSetTest.java
src/test/java/org/folio/oaipmh/service/impl/InstancesServiceImplTest.java
src/test/java/org/folio/oaipmh/service/impl/SetServiceImplTest.java
src/test/java/org/folio/rest/impl/CleanUpJobTest.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java
src/test/java/org/folio/rest/impl/OaiPmhSetImplTest.java

Tests that are run after OaiPmhImplTest and uses the database cannot obtain normal connections cause some threads after OaiPmhImplTest still hand the connections from the pool associated with the test tenant oaiTest.
Reset the connection pool before each test that uses the database.

Fix DB pool conflicts

---

src/main/java/org/folio/oaipmh/Constants.java
src/main/java/org/folio/oaipmh/Request.java
src/main/java/org/folio/oaipmh/dao/InstancesDao.java
src/main/java/org/folio/oaipmh/dao/impl/InstancesDaoImpl.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/main/java/org/folio/oaipmh/service/InstancesService.java
src/main/java/org/folio/oaipmh/service/impl/InstancesServiceImpl.java

Jira: https://issues.folio.org/browse/MODOAIPMH-294
It is required to make the resumption token reusable. The previous implementation didn't allow reuse of the res. token by the reason that processed instances were deleted and therefore they couldn't be reused anymore.
Remove deleting of instances after they have been processed.
Requesting instances ids:
2.1 first batch = true
select first instances by request_id and order by id.
if the number of instances returned > batchSize (which means that it not the last batch) we grab the id of the last instance and put it to resumption token.
2.2 first batch = false
we grab the id from the resumption token and make the same select query as before but with additional criteria where id >= id value from resumption token.

MODOAIPMH-294: make resumptionToken be reusable

---

README.md
pom.xml
src/main/java/org/folio/oaipmh/Constants.java
src/main/java/org/folio/oaipmh/ResponseConverter.java
src/main/java/org/folio/oaipmh/client/SourceStorageSourceRecordsClient.java
src/main/java/org/folio/oaipmh/helpers/streaming/BatchStreamWrapper.java
src/main/java/org/folio/oaipmh/mappers/PropertyNameMapper.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/main/resources/config/technical.json
src/test/java/org/folio/oaipmh/helpers/RepositoryConfigurationUtilTest.java
src/test/java/org/folio/oaipmh/helpers/response/ResponseHelperTest.java
src/test/java/org/folio/rest/impl/CleanUpJobTest.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java
src/test/java/org/folio/rest/impl/OkapiMockServer.java
src/test/resources/config/technical.json
src/test/resources/inventory_view/instance_id_to_make_srs_fail_with_timeout.json

Jira: https://issues.folio.org/browse/MODOAIPMH-300
Jira: https://issues.folio.org/browse/MODOAIPMH-301
Fix issue with the hanging of srs response handler which caused the harvest to be canceled. 
The root cause is that when srs responds with a large response body it may hang for an unknown reason and the body is not written to the response, therefore we can get the body and invoke body handler which causes the code hanging and canceling harvesting as result.
Set the idle timeout of srs request to 20 seconds (instead of 5000) in order to invoke the exception handler (by causing timeout exception) when there a problem with receiving response body from SRS. Make a retry of srs call in the exception handler.

MODOAIPMH-300: Not all instances ids are saved for initial harvest

---

src/main/java/org/folio/oaipmh/Request.java
src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java
src/main/java/org/folio/oaipmh/helpers/AbstractHelper.java
src/main/java/org/folio/oaipmh/helpers/GetOaiMetadataFormatsHelper.java
src/main/java/org/folio/oaipmh/helpers/GetOaiRepositoryInfoHelper.java
src/main/java/org/folio/oaipmh/helpers/RepositoryConfigurationUtil.java
src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/main/java/org/folio/rest/impl/OaiPmhImpl.java
src/test/java/org/folio/oaipmh/helpers/RepositoryConfigurationUtilTest.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java

Jira: https://issues.folio.org/browse/MODOAIPMH-310
Since oai-pmh can process several requests at once they all share the common configMap which is incorrect. The reason is that each upcoming request loads the config and overrides its values each time which can be already in use by handlers in separate threads. 
Each request should have its own config set in configMap as it was when we were using vertxContext config.
As well the "shouldUseValidConfigValueAndDoNotSkipSuppressedRecords_whenGetListRecordsMarc21WithHoldings" was removed for the reason that it should test logic with real third-party service like mod-config and we already have such an integration test at the folio-integration-tests project.

MODOAIPMH-310: Stabilize oai-pmh tests for release.

---

src/main/java/org/folio/oaipmh/helpers/AbstractHelper.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java
src/test/java/org/folio/rest/impl/OkapiMockServer.java

Jira: https://issues.folio.org/browse/MODOAIPMH-327
Fix issue with resumption token flow work for marc21 and oai_dc metadata prefixes.
At previous commits, the way for using configurations was changed to use the request_id instead of tenant_id and one place wasn't adjusted to the new approach and this caused the issue. So, the code was adjusted to use request id. Parameterized unit test added.

MODOAIPMH-327: Resumption token flow doesn't work as expected for marc21 and oai_dc metadata prefixes

---

descriptors/ModuleDescriptor-template.json

Jira: https://issues.folio.org/browse/MODOAIPMH-283
The existing FOLIO implementation of the derived fields (effective location and effective call number) requires item records. The purpose of this story is to populate location and holdings information, following the logic of effective location/call number when the item data is not present.

MODOAIPMH-283 - provide effective location and effective call number data when item record is not present

---

src/main/java/org/folio/oaipmh/service/MetricsCollectingService.java

Enable scheduling from [PR#240](https://github.com/folio-org/mod-oai-pmh/pull/240) - missed @Configuration annotation.

MODOAIPMH-377 - Implement metrics for mod-oai-pmh

---

Jenkinsfile
src/test/java/org/folio/rest/impl/ModTenantAPIIT.java

The "Docker Build" stage in Jenkins takes 45 seconds. It builds the Docker container and runs the health test.
ModTenantAPIIT.java is an integration test that builds the Docker container.
Moving the health test from Jenkins into ModTenantAPIIT saves 44 seconds because the existing Docker container can be used.

MODOAIPMH-393: Move health test from Jenkins file to integration test

---

README.md
descriptors/ModuleDescriptor-template.json

[MODOAIPMH-405](https://issues.folio.org/browse/MODOAIPMH-405) - Spike - Investigate mod-oai-pmh logs when debug mode is enabled.
ENV variables should be increased according to the ModuleDescriptor.

MODOAIPMH-405 - Spike - Investigate mod-oai-pmh logs when debug mode is enabled

---

src/main/java/org/folio/oaipmh/processors/MarcWithHoldingsRequestHelper.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java

Jira: https://issues.folio.org/browse/MODOAIPMH-418
Add onlyInstanceUpdateDate to the "get instances ids" request query params as false. 
Therefore the items and holdings updateDate value are taken into effect when looking for instances.

MODOAIPMH-418: add onlyInstanceUpdateDate to get instances ids request

---

src/main/java/org/folio/oaipmh/helpers/records/RecordMetadataManager.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java

[MODOAIPMH-436](https://issues.folio.org/browse/MODOAIPMH-436) - Holdings without items have  always subfield t in 952 set to 1
For holdings without items when the records are harvested with discovery flag the subfield t in 952 field is always set to 1 even if the holdings are not suppressed.
* fixed harvesting logic
* updated unit test
- Are the JIRAs under active development?  
Ideally all of …

MODOAIPMH-436 - Holdings without items have  always subfield t in 952 set to 1

---

descriptors/ModuleDescriptor-template.json

mod-inventory-storage has new major interface versions:
instance-storage 9.0
holdings-storage 6.0
item-storage 10.0
mod-oai-pmh uses only instance-storage, it doesn't use the other two interfaces.
mod-oai-pmh is not affected because the incompatible change is in the DELETE all APIs only that is not used by mod-oai-pmh.
Only the okapiInterfaces need to be bumped in "requires" section of ModuleDescriptor-template.json

MODOAIPMH-440: Support instance-storage 9.0 interface

---

README.md
src/main/java/org/folio/oaipmh/Constants.java
src/main/java/org/folio/oaipmh/mappers/PropertyNameMapper.java
src/main/java/org/folio/rest/impl/ModTenantAPI.java
src/main/resources/config/behavior.json
src/test/java/org/folio/rest/impl/InitAPIsTest.java
src/test/resources/config/behavior.json

[MODOAIPMH-460](https://issues.folio.org/browse/MODOAIPMH-460) - Make records source configurable
In order to increase OAI-PMH module flexibility, records_source parameter is intended to be added to OAI-PMH settings. …

MODOAIPMH-460 - Make records source configurable

---

src/main/java/org/folio/oaipmh/helpers/records/RecordMetadataManager.java
src/test/java/org/folio/oaipmh/helpers/records/RecordMetadataManagerTest.java
src/test/resources/metadata-manager/electronic_access-new_relationship.json

[MODOAIPMH-473](https://issues.folio.org/browse/MODOAIPMH-473) - "856" field is omitted in responce for Electronic access relationship type created by user
Electronic access relationship is driven by inventory settings, so users can edit (add, remove) any option.
In case user added a new Electronic access relationship and link it to a Holdings record then started to harvest the instance with such Holdings record, the "856" Holdings data field is not shown in the response
Add possibility to return default value ("4, ") from map of indicators in case of new Electronic access relationship.
If there are …

MODOAIPMH-473 - "856" field is omitted in responce for Electronic access relationship type created by user

---

.github/workflows/api-doc.yml
.github/workflows/api-lint.yml
.github/workflows/api-schema-lint.yml
Jenkinsfile
README.md
ramls/oai-pmh.raml

[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).

FOLIO-3678 MODOAIPMH-512 Use GitHub Workflows api-lint and api-schema-lint and api-doc

---

src/main/java/org/folio/oaipmh/querybuilder/QueryBuilder.java
src/main/java/org/folio/oaipmh/querybuilder/RecordsSource.java
src/test/java/org/folio/oaipmh/querybuilder/QueryBuilderTest.java
src/test/java/org/folio/oaipmh/querybuilder/RecordsSourceTest.java

[MODOAIPMH-534](https://issues.folio.org/browse/MODOAIPMH-534) - Handle CONSORTIUM-FOLIO instances in the harvest
When selecting Inventory records source, not only instances with FOLIO source need to be retrieved, but also with CONSORTIUM-FOLIO as well.
Modify QueryBuilder.
Ideally all of the PRs involved in breaking changes would be merged in the same day …

MODOAIPMH-534 Added shared folio

---

src/main/resources/liquibase/tenant/scripts/2023-06-13--12-00-update-metadata-add-started-date.xml

[MODOAIPMH-545](https://issues.folio.org/browse/MODOAIPMH-545) - Missing columns in request_metadata_lb in Poppy upgraded environments
When upgrading from Orchid to Poppy, we are missing two columns for the table request_metadata_lb. Columns path_to_error_file_in_s3 and started_date are missing. We've seen this in multiple environments now.
Updated liquibase migration to clear data in request_metadata_lb table
- Are the JIRAs …

MODOAIPMH-545 - Missing columns in request_metadata_lb in Poppy upgraded environments

---

src/main/java/org/folio/oaipmh/WebClientProvider.java
src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java
src/main/java/org/folio/oaipmh/processors/GetListRecordsRequestHelper.java
src/main/java/org/folio/oaipmh/service/SourceStorageSourceRecordsClientWrapper.java

[MODOAIPMH-578](https://folio-org.atlassian.net/browse/MODOAIPMH-578) - OAI-PMH GetRecord call does not return MARC records after token was expired and refreshed
To avoid storing of tokens for further reusing.
Remove storage of API keys for tenants (caching with infinite time), reinitialise SRS-client for each invocation, make clients autoclosable.
Ideally …

MODOAIPMH-578 - OAI-PMH GetRecord call does not return MARC records after token was expired and refreshed

---

.github/workflows/postgres.yml
pom.xml
ramls/folio-set-filtering-conditions.raml
ramls/folio-set.raml
ramls/request-metadata.raml
src/main/java/org/folio/rest/impl/OaiPmhSetImpl.java
src/main/java/org/folio/rest/impl/RequestMetadataAPIs.java

[FOLIO-4087](https://folio-org.atlassian.net/browse/FOLIO-4087) - RMB & spring-base upgrades
Updating RMB dependency according to https://github.com/folio-org/raml-module-builder/blob/v35.3.0/doc/upgrading.md#version-353
Updating dependencies, apply requirements from https://github.com/folio-org/raml-module-builder/blob/v35.3.0/doc/upgrading.md#version-353.
- Do PRs exist for these …

FOLIO-4087 - RMB & spring-base upgrades

---

NEWS.md
descriptors/ModuleDescriptor-template.json

[MODOAIPMH-576](https://folio-org.atlassian.net/browse/MODOAIPMH-576)
According to the epic <a data-inline-card="" href="https://folio-org.atlassian.net/browse/FOLIO-4044," data-card-data="">https://folio-org.atlassian.net/browse/FOLIO-4044,</a> some permissions have been changed in the `source-storage-records v3.3` and `source-storage-source-records v3.2`</p><p>mod-oai-pmh uses the following outdated permissions:</p><pre><code>"source-storage.records.get"
"source-storage.sourceRecords.get”</code></pre>
Permission | Enpoint
-- | --
source-storage.source-records.item.get | /source-storage/source-records/{id}
source-storage.source-records.collection.get | /source-storage/source-records
<p></p>
- Does …

MODOAIPMH-576 Update source-storage-records and  source-storage-source-records versions and rename module permissions

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/oaipmh/helpers/records/RecordMetadataManager.java
src/test/java/org/folio/oaipmh/helpers/records/RecordMetadataManagerTest.java
src/test/resources/metadata-manager/inventory_instance_with_1_item.json
src/test/resources/metadata-manager/inventory_instance_with_2_items.json
src/test/resources/metadata-manager/inventory_instance_with_item_without_call_number.json

[MODOAIPMH-587](https://folio-org.atlassian.net/browse/MODOAIPMH-587) - Include FOLIO location in addition to Discovery Display Name
FOLIO's OAI-PMH implementation populates location data as specified in   based on Discovery display name.  However, some libraries would prefer to have FOLIO location to be included in the response as well.
Update view in mod-inventory-storage and add locationName field, retrieve locationName and populate 952 $s.
- Do JIRAs exist to update the …

MODOAIPMH-587 - Include FOLIO location in addition to Discovery Display Name

---

src/main/java/org/folio/oaipmh/helpers/AbstractGetRecordsHelper.java
src/test/java/org/folio/rest/impl/OaiPmhImplTest.java
src/test/java/org/folio/rest/impl/OkapiMockServer.java
src/test/resources/instance-storage/instances/instance_linked_data.json
src/test/resources/instance-storage/instances/instances_no_srs.json
src/test/resources/source-storage/source-records/linked_data_srs_record.json

[MODOAIPMH-581](https://folio-org.atlassian.net/browse/MODOAIPMH-581) - Harvesting instances with LINKED_DATA source
Exclude inventory data if srs is present for GetRecord.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …

MODOAIPMH-581 - Harvesting instances with LINKED_DATA source

---

descriptors/ModuleDescriptor-template.json
src/main/resources/templates/db_scripts/schema.json
src/main/resources/templates/db_scripts/update_instance_deleted.sql

[MODOAIPMH-614](https://folio-org.atlassian.net/browse/MODOAIPMH-614) - Set for deletion FOLIO Instances are harvested with ListRecords, ListIdentifiers requests as not deleted
Deleted in the following ways FOLIO Instances harvested with ListRecords, ListIdentifiers requests as not deleted.
Update instances views and add additional UNION ALL to harvest instances with "deleted"=true as well.
- Are the JIRAs under active …

MODOAIPMH-614 - Set for deletion FOLIO Instances are harvested with ListRecords, ListIdentifiers requests as not deleted
